interface WonderImage {
  id: number;
  name: string;
  src: string;
  description: string;
  photographer: string;
  location: string;
  date: string;
  tags: string[];
}

const wonderImages: WonderImage[] = [
  {
    id: 1,
    name: "Eiffel Tower",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "John Doe",
    location: "Paris, France",
    date: "2023-10-01",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 2,
    name: "Great Wall of China",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Jane Smith",
    location: "Beijing, China",
    date: "2023-10-02",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 3,
    name: "Machu Picchu",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Alice Johnson",
    location: "Peru",
    date: "2023-10-03",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 4,
    name: "Christ the Redeemer",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Bob Brown",
    location: "Rio de Janeiro, Brazil",
    date: "2023-10-04",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 5,
    name: "Colosseum",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Charlie Davis",
    location: "Rome, Italy",
    date: "2023-10-05",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 6,
    name: "Taj Mahal",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "David Wilson",
    location: "Agra, India",
    date: "2023-10-06",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 7,
    name: "Petra",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Emma Thomas",
    location: "Petra, Jordan",
    date: "2023-10-07",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 8,
    name: "Chichen Itza",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Sophia Martinez",
    location: "Yucatan, Mexico",
    date: "2023-10-08",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 9,
    name: "Sydney Opera House",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Liam Garcia",
    location: "Sydney, Australia",
    date: "2023-10-09",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 10,
    name: "Mount Everest",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Noah Lee",
    location: "Nepal",
    date: "2023-10-10",
    tags: ["landmark", "nature", "travel"],
  },
  {
    id: 11,
    name: "Niagara Falls",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Olivia Harris",
    location: "Ontario, Canada",
    date: "2023-10-11",
    tags: ["landmark", "nature", "travel"],
  },
  {
    id: 12,
    name: "Santorini",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Isabella Clark",
    location: "Santorini, Greece",
    date: "2023-10-12",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 13,
    name: "Grand Canyon",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "James Walker",
    location: "Arizona, USA",
    date: "2023-10-13",
    tags: ["landmark", "nature", "travel"],
  },
  {
    id: 14,
    name: "Burj Khalifa",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Mia Young",
    location: "Dubai, UAE",
    date: "2023-10-14",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 15,
    name: "Angkor Wat",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Ethan Hall",
    location: "Siem Reap, Cambodia",
    date: "2023-10-15",
    tags: ["landmark", "architecture", "travel"],
  },
  {
    id: 16,
    name: "Stonehenge",
    src: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHdpbmRvd3xlbnwwfHx8fDE2ODQ5NTY1MjM&ixlib=rb-4.0.3&q=80&w=1080",
    description: "A beautiful view of the wonders of the world.",
    photographer: "Ava Allen",
    location: "Wiltshire, England",
    date: "2023-10-16",
    tags: ["landmark", "history", "travel"],
  },
];

export default wonderImages;
