import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FormExample from "./_components/formexample";
import Header from "./_components/header";
import ErrorWrapper from "./error-wrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "A powerful App developed with Next.js 15",
    template: "%s | Next.js 15",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <FormExample />
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer>
          <div className="bg-gray-800 p-4">
            <div className="container mx-auto">
              <p className="text-white text-center">
                &copy; 2023 My Next.js App. All rights reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
