import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-gray-800 p-4">
            <div className="container mx-auto">
              <h1 className="text-white text-2xl">My Next.js App</h1>
            </div>
            <div className="container mx-auto">
              <ul className="flex space-x-4">
                <li>
                  <a href="/profile" className="text-white hover:text-gray-300">
                    Profile
                  </a>
                </li>
                <li>
                  <a
                    href="/settings"
                    className="text-white hover:text-gray-300"
                  >
                    Settings
                  </a>
                </li>
                <li>
                  <a href="/logout" className="text-white hover:text-gray-300">
                    Logout
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        {children}
        <footer>
          <div className="bg-gray-800 p-4">
            <div className="container mx-auto">
              <p className="text-white text-center">
                &copy; 2023 My Next.js App. All rights reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
